// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `CommModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CommModule;

public interface BaseInterfacePrx extends Ice.ObjectPrx
{
    public void sendMovementData(int forward, int strafe, int rotate);

    public void sendMovementData(int forward, int strafe, int rotate, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMovementData(int forward, int strafe, int rotate);

    public Ice.AsyncResult begin_sendMovementData(int forward, int strafe, int rotate, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMovementData(int forward, int strafe, int rotate, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMovementData(int forward, int strafe, int rotate, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMovementData(int forward, int strafe, int rotate, Callback_BaseInterface_sendMovementData __cb);

    public Ice.AsyncResult begin_sendMovementData(int forward, int strafe, int rotate, java.util.Map<String, String> __ctx, Callback_BaseInterface_sendMovementData __cb);

    public Ice.AsyncResult begin_sendMovementData(int forward,
                                                  int strafe, 
                                                  int rotate, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMovementData(int forward,
                                                  int strafe, 
                                                  int rotate, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendMovementData(int forward,
                                                  int strafe, 
                                                  int rotate, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMovementData(int forward,
                                                  int strafe, 
                                                  int rotate, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendMovementData(Ice.AsyncResult __result);

    public void setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight);

    public void setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight, Ice.Callback __cb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight, Callback_BaseInterface_setMotorSpeeds __cb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft, int frontRight, int backLeft, int backRight, java.util.Map<String, String> __ctx, Callback_BaseInterface_setMotorSpeeds __cb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft,
                                                int frontRight, 
                                                int backLeft, 
                                                int backRight, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft,
                                                int frontRight, 
                                                int backLeft, 
                                                int backRight, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft,
                                                int frontRight, 
                                                int backLeft, 
                                                int backRight, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setMotorSpeeds(int frontLeft,
                                                int frontRight, 
                                                int backLeft, 
                                                int backRight, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_setMotorSpeeds(Ice.AsyncResult __result);

    public void moveArm(String pos);

    public void moveArm(String pos, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_moveArm(String pos);

    public Ice.AsyncResult begin_moveArm(String pos, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_moveArm(String pos, Ice.Callback __cb);

    public Ice.AsyncResult begin_moveArm(String pos, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_moveArm(String pos, Callback_BaseInterface_moveArm __cb);

    public Ice.AsyncResult begin_moveArm(String pos, java.util.Map<String, String> __ctx, Callback_BaseInterface_moveArm __cb);

    public Ice.AsyncResult begin_moveArm(String pos,
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_moveArm(String pos,
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_moveArm(String pos,
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_moveArm(String pos,
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_moveArm(Ice.AsyncResult __result);

    public void sendControlInfo(int port, int on);

    public void sendControlInfo(int port, int on, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendControlInfo(int port, int on);

    public Ice.AsyncResult begin_sendControlInfo(int port, int on, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendControlInfo(int port, int on, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendControlInfo(int port, int on, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendControlInfo(int port, int on, Callback_BaseInterface_sendControlInfo __cb);

    public Ice.AsyncResult begin_sendControlInfo(int port, int on, java.util.Map<String, String> __ctx, Callback_BaseInterface_sendControlInfo __cb);

    public Ice.AsyncResult begin_sendControlInfo(int port,
                                                 int on, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendControlInfo(int port,
                                                 int on, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendControlInfo(int port,
                                                 int on, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendControlInfo(int port,
                                                 int on, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_VoidCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendControlInfo(Ice.AsyncResult __result);

    public void init(String ip, String name, int port, int id);

    public void init(String ip, String name, int port, int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_init(String ip, String name, int port, int id);

    public Ice.AsyncResult begin_init(String ip, String name, int port, int id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_init(String ip, String name, int port, int id, Ice.Callback __cb);

    public Ice.AsyncResult begin_init(String ip, String name, int port, int id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_init(String ip, String name, int port, int id, Callback_BaseInterface_init __cb);

    public Ice.AsyncResult begin_init(String ip, String name, int port, int id, java.util.Map<String, String> __ctx, Callback_BaseInterface_init __cb);

    public Ice.AsyncResult begin_init(String ip,
                                      String name, 
                                      int port, 
                                      int id, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_init(String ip,
                                      String name, 
                                      int port, 
                                      int id, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_init(String ip,
                                      String name, 
                                      int port, 
                                      int id, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_init(String ip,
                                      String name, 
                                      int port, 
                                      int id, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public void end_init(Ice.AsyncResult __result);

    public void pokeBot(String baseIP);

    public void pokeBot(String baseIP, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_pokeBot(String baseIP);

    public Ice.AsyncResult begin_pokeBot(String baseIP, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_pokeBot(String baseIP, Ice.Callback __cb);

    public Ice.AsyncResult begin_pokeBot(String baseIP, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_pokeBot(String baseIP, Callback_BaseInterface_pokeBot __cb);

    public Ice.AsyncResult begin_pokeBot(String baseIP, java.util.Map<String, String> __ctx, Callback_BaseInterface_pokeBot __cb);

    public Ice.AsyncResult begin_pokeBot(String baseIP,
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_pokeBot(String baseIP,
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_pokeBot(String baseIP,
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_pokeBot(String baseIP,
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_pokeBot(Ice.AsyncResult __result);

    public void shoot();

    public void shoot(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shoot();

    public Ice.AsyncResult begin_shoot(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shoot(Ice.Callback __cb);

    public Ice.AsyncResult begin_shoot(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_shoot(Callback_BaseInterface_shoot __cb);

    public Ice.AsyncResult begin_shoot(java.util.Map<String, String> __ctx, Callback_BaseInterface_shoot __cb);

    public Ice.AsyncResult begin_shoot(IceInternal.Functional_VoidCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_shoot(IceInternal.Functional_VoidCallback __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_shoot(java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_shoot(java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_shoot(Ice.AsyncResult __result);

    public void reload();

    public void reload(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_reload();

    public Ice.AsyncResult begin_reload(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_reload(Ice.Callback __cb);

    public Ice.AsyncResult begin_reload(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_reload(Callback_BaseInterface_reload __cb);

    public Ice.AsyncResult begin_reload(java.util.Map<String, String> __ctx, Callback_BaseInterface_reload __cb);

    public Ice.AsyncResult begin_reload(IceInternal.Functional_VoidCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_reload(IceInternal.Functional_VoidCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_reload(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_reload(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_reload(Ice.AsyncResult __result);

    public void allOff();

    public void allOff(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_allOff();

    public Ice.AsyncResult begin_allOff(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_allOff(Ice.Callback __cb);

    public Ice.AsyncResult begin_allOff(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_allOff(Callback_BaseInterface_allOff __cb);

    public Ice.AsyncResult begin_allOff(java.util.Map<String, String> __ctx, Callback_BaseInterface_allOff __cb);

    public Ice.AsyncResult begin_allOff(IceInternal.Functional_VoidCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_allOff(IceInternal.Functional_VoidCallback __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_allOff(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_allOff(java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_VoidCallback __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_allOff(Ice.AsyncResult __result);

    public void laserTagFire();

    public void laserTagFire(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_laserTagFire();

    public Ice.AsyncResult begin_laserTagFire(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_laserTagFire(Ice.Callback __cb);

    public Ice.AsyncResult begin_laserTagFire(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_laserTagFire(Callback_BaseInterface_laserTagFire __cb);

    public Ice.AsyncResult begin_laserTagFire(java.util.Map<String, String> __ctx, Callback_BaseInterface_laserTagFire __cb);

    public Ice.AsyncResult begin_laserTagFire(IceInternal.Functional_VoidCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_laserTagFire(IceInternal.Functional_VoidCallback __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_laserTagFire(java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_laserTagFire(java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public void end_laserTagFire(Ice.AsyncResult __result);

    public void laserTagShield();

    public void laserTagShield(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_laserTagShield();

    public Ice.AsyncResult begin_laserTagShield(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_laserTagShield(Ice.Callback __cb);

    public Ice.AsyncResult begin_laserTagShield(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_laserTagShield(Callback_BaseInterface_laserTagShield __cb);

    public Ice.AsyncResult begin_laserTagShield(java.util.Map<String, String> __ctx, Callback_BaseInterface_laserTagShield __cb);

    public Ice.AsyncResult begin_laserTagShield(IceInternal.Functional_VoidCallback __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_laserTagShield(IceInternal.Functional_VoidCallback __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_laserTagShield(java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_laserTagShield(java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_laserTagShield(Ice.AsyncResult __result);

    public void sendSteeringData(int direction);

    public void sendSteeringData(int direction, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSteeringData(int direction);

    public Ice.AsyncResult begin_sendSteeringData(int direction, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSteeringData(int direction, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSteeringData(int direction, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSteeringData(int direction, Callback_BaseInterface_sendSteeringData __cb);

    public Ice.AsyncResult begin_sendSteeringData(int direction, java.util.Map<String, String> __ctx, Callback_BaseInterface_sendSteeringData __cb);

    public Ice.AsyncResult begin_sendSteeringData(int direction,
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendSteeringData(int direction,
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendSteeringData(int direction,
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendSteeringData(int direction,
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendSteeringData(Ice.AsyncResult __result);

    public void sendTurretData(int horizontal, int vertical);

    public void sendTurretData(int horizontal, int vertical, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendTurretData(int horizontal, int vertical);

    public Ice.AsyncResult begin_sendTurretData(int horizontal, int vertical, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendTurretData(int horizontal, int vertical, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal, int vertical, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal, int vertical, Callback_BaseInterface_sendTurretData __cb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal, int vertical, java.util.Map<String, String> __ctx, Callback_BaseInterface_sendTurretData __cb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal,
                                                int vertical, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal,
                                                int vertical, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal,
                                                int vertical, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendTurretData(int horizontal,
                                                int vertical, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendTurretData(Ice.AsyncResult __result);

    public void setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft);

    public void setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft, Ice.Callback __cb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft, Callback_BaseInterface_setDuneBotMotorSpeeds __cb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft, int frontRight, int backRight, int backLeft, java.util.Map<String, String> __ctx, Callback_BaseInterface_setDuneBotMotorSpeeds __cb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft,
                                                       int frontRight, 
                                                       int backRight, 
                                                       int backLeft, 
                                                       IceInternal.Functional_VoidCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft,
                                                       int frontRight, 
                                                       int backRight, 
                                                       int backLeft, 
                                                       IceInternal.Functional_VoidCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft,
                                                       int frontRight, 
                                                       int backRight, 
                                                       int backLeft, 
                                                       java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_VoidCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setDuneBotMotorSpeeds(int frontLeft,
                                                       int frontRight, 
                                                       int backRight, 
                                                       int backLeft, 
                                                       java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_VoidCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb);

    public void end_setDuneBotMotorSpeeds(Ice.AsyncResult __result);

    public void requestImageProcessing();

    public void requestImageProcessing(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_requestImageProcessing();

    public Ice.AsyncResult begin_requestImageProcessing(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_requestImageProcessing(Ice.Callback __cb);

    public Ice.AsyncResult begin_requestImageProcessing(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_requestImageProcessing(Callback_BaseInterface_requestImageProcessing __cb);

    public Ice.AsyncResult begin_requestImageProcessing(java.util.Map<String, String> __ctx, Callback_BaseInterface_requestImageProcessing __cb);

    public Ice.AsyncResult begin_requestImageProcessing(IceInternal.Functional_VoidCallback __responseCb,
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_requestImageProcessing(IceInternal.Functional_VoidCallback __responseCb,
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_requestImageProcessing(java.util.Map<String, String> __ctx,
                                                        IceInternal.Functional_VoidCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_requestImageProcessing(java.util.Map<String, String> __ctx,
                                                        IceInternal.Functional_VoidCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_requestImageProcessing(Ice.AsyncResult __result);

    public void restartBot();

    public void restartBot(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_restartBot();

    public Ice.AsyncResult begin_restartBot(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_restartBot(Ice.Callback __cb);

    public Ice.AsyncResult begin_restartBot(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_restartBot(Callback_BaseInterface_restartBot __cb);

    public Ice.AsyncResult begin_restartBot(java.util.Map<String, String> __ctx, Callback_BaseInterface_restartBot __cb);

    public Ice.AsyncResult begin_restartBot(IceInternal.Functional_VoidCallback __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_restartBot(IceInternal.Functional_VoidCallback __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_restartBot(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_restartBot(java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_restartBot(Ice.AsyncResult __result);

    public void shutdownBot();

    public void shutdownBot(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shutdownBot();

    public Ice.AsyncResult begin_shutdownBot(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_shutdownBot(Ice.Callback __cb);

    public Ice.AsyncResult begin_shutdownBot(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_shutdownBot(Callback_BaseInterface_shutdownBot __cb);

    public Ice.AsyncResult begin_shutdownBot(java.util.Map<String, String> __ctx, Callback_BaseInterface_shutdownBot __cb);

    public Ice.AsyncResult begin_shutdownBot(IceInternal.Functional_VoidCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_shutdownBot(IceInternal.Functional_VoidCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_shutdownBot(java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_shutdownBot(java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_shutdownBot(Ice.AsyncResult __result);
}
