// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `CommModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package CommModule;

public interface SensorInterfacePrx extends Ice.ObjectPrx
{
    public void initializeBot(int botnum);

    public void initializeBot(int botnum, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_initializeBot(int botnum);

    public Ice.AsyncResult begin_initializeBot(int botnum, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_initializeBot(int botnum, Ice.Callback __cb);

    public Ice.AsyncResult begin_initializeBot(int botnum, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_initializeBot(int botnum, Callback_SensorInterface_initializeBot __cb);

    public Ice.AsyncResult begin_initializeBot(int botnum, java.util.Map<String, String> __ctx, Callback_SensorInterface_initializeBot __cb);

    public Ice.AsyncResult begin_initializeBot(int botnum,
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_initializeBot(int botnum,
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_initializeBot(int botnum,
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_initializeBot(int botnum,
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_VoidCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public void end_initializeBot(Ice.AsyncResult __result);

    public void sendLaserTagData(int botnum, String laserTagDataType, int hitCount);

    public void sendLaserTagData(int botnum, String laserTagDataType, int hitCount, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum, String laserTagDataType, int hitCount);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum, String laserTagDataType, int hitCount, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum, String laserTagDataType, int hitCount, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum, String laserTagDataType, int hitCount, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum, String laserTagDataType, int hitCount, Callback_SensorInterface_sendLaserTagData __cb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum, String laserTagDataType, int hitCount, java.util.Map<String, String> __ctx, Callback_SensorInterface_sendLaserTagData __cb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum,
                                                  String laserTagDataType, 
                                                  int hitCount, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum,
                                                  String laserTagDataType, 
                                                  int hitCount, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum,
                                                  String laserTagDataType, 
                                                  int hitCount, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendLaserTagData(int botnum,
                                                  String laserTagDataType, 
                                                  int hitCount, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_VoidCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendLaserTagData(Ice.AsyncResult __result);

    public void sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq);

    public void sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq, Callback_SensorInterface_sendStreamingVideoData __cb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum, byte[] bytes, int cameraID, int numObjectsDetected, ImgProcData[] imgProcseq, java.util.Map<String, String> __ctx, Callback_SensorInterface_sendStreamingVideoData __cb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum,
                                                        byte[] bytes, 
                                                        int cameraID, 
                                                        int numObjectsDetected, 
                                                        ImgProcData[] imgProcseq, 
                                                        IceInternal.Functional_VoidCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum,
                                                        byte[] bytes, 
                                                        int cameraID, 
                                                        int numObjectsDetected, 
                                                        ImgProcData[] imgProcseq, 
                                                        IceInternal.Functional_VoidCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum,
                                                        byte[] bytes, 
                                                        int cameraID, 
                                                        int numObjectsDetected, 
                                                        ImgProcData[] imgProcseq, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_VoidCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendStreamingVideoData(int botnum,
                                                        byte[] bytes, 
                                                        int cameraID, 
                                                        int numObjectsDetected, 
                                                        ImgProcData[] imgProcseq, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_VoidCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendStreamingVideoData(Ice.AsyncResult __result);

    public void pokeBase(int botnum);

    public void pokeBase(int botnum, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_pokeBase(int botnum);

    public Ice.AsyncResult begin_pokeBase(int botnum, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_pokeBase(int botnum, Ice.Callback __cb);

    public Ice.AsyncResult begin_pokeBase(int botnum, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_pokeBase(int botnum, Callback_SensorInterface_pokeBase __cb);

    public Ice.AsyncResult begin_pokeBase(int botnum, java.util.Map<String, String> __ctx, Callback_SensorInterface_pokeBase __cb);

    public Ice.AsyncResult begin_pokeBase(int botnum,
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_pokeBase(int botnum,
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_pokeBase(int botnum,
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_pokeBase(int botnum,
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_pokeBase(Ice.AsyncResult __result);

    public void sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight);

    public void sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight, Callback_SensorInterface_sendHallSensorData __cb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum, float frontLeft, float frontRight, float backLeft, float backRight, java.util.Map<String, String> __ctx, Callback_SensorInterface_sendHallSensorData __cb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum,
                                                    float frontLeft, 
                                                    float frontRight, 
                                                    float backLeft, 
                                                    float backRight, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum,
                                                    float frontLeft, 
                                                    float frontRight, 
                                                    float backLeft, 
                                                    float backRight, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum,
                                                    float frontLeft, 
                                                    float frontRight, 
                                                    float backLeft, 
                                                    float backRight, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendHallSensorData(int botnum,
                                                    float frontLeft, 
                                                    float frontRight, 
                                                    float backLeft, 
                                                    float backRight, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendHallSensorData(Ice.AsyncResult __result);

    public void sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az);

    public void sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az);

    public Ice.AsyncResult begin_sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az, Callback_SensorInterface_sendImuData __cb);

    public Ice.AsyncResult begin_sendImuData(int botnum, float yaw, float pitch, float roll, float ax, float ay, float az, java.util.Map<String, String> __ctx, Callback_SensorInterface_sendImuData __cb);

    public Ice.AsyncResult begin_sendImuData(int botnum,
                                             float yaw, 
                                             float pitch, 
                                             float roll, 
                                             float ax, 
                                             float ay, 
                                             float az, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendImuData(int botnum,
                                             float yaw, 
                                             float pitch, 
                                             float roll, 
                                             float ax, 
                                             float ay, 
                                             float az, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendImuData(int botnum,
                                             float yaw, 
                                             float pitch, 
                                             float roll, 
                                             float ax, 
                                             float ay, 
                                             float az, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendImuData(int botnum,
                                             float yaw, 
                                             float pitch, 
                                             float roll, 
                                             float ax, 
                                             float ay, 
                                             float az, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_sendImuData(Ice.AsyncResult __result);
}
