// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `VisionModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VisionModule;

public interface BaseInterface extends Ice.Object,
                                       _BaseInterfaceOperations, _BaseInterfaceOperationsNC
{
    public static final String ice_staticId = "::VisionModule::BaseInterface";

    public static final long serialVersionUID = -558206285L;
}
