// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `VisionModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VisionModule;

public final class ColorRGBHolder extends Ice.Holder<ColorRGB>
{
    public
    ColorRGBHolder()
    {
    }

    public
    ColorRGBHolder(ColorRGB value)
    {
        super(value);
    }
}
