// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `VisionModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VisionModule;

public interface VisionInterfacePrx extends Ice.ObjectPrx
{
    public double ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l);

    public double ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l);

    public Ice.AsyncResult begin_ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l, Ice.Callback __cb);

    public Ice.AsyncResult begin_ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l, Callback_VisionInterface_ping __cb);

    public Ice.AsyncResult begin_ping(double a, double b, double c, double d, double e, double f, double g, double h, double i, double j, double k, double l, java.util.Map<String, String> __ctx, Callback_VisionInterface_ping __cb);

    public Ice.AsyncResult begin_ping(double a,
                                      double b, 
                                      double c, 
                                      double d, 
                                      double e, 
                                      double f, 
                                      double g, 
                                      double h, 
                                      double i, 
                                      double j, 
                                      double k, 
                                      double l, 
                                      IceInternal.Functional_DoubleCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_ping(double a,
                                      double b, 
                                      double c, 
                                      double d, 
                                      double e, 
                                      double f, 
                                      double g, 
                                      double h, 
                                      double i, 
                                      double j, 
                                      double k, 
                                      double l, 
                                      IceInternal.Functional_DoubleCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_ping(double a,
                                      double b, 
                                      double c, 
                                      double d, 
                                      double e, 
                                      double f, 
                                      double g, 
                                      double h, 
                                      double i, 
                                      double j, 
                                      double k, 
                                      double l, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_DoubleCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_ping(double a,
                                      double b, 
                                      double c, 
                                      double d, 
                                      double e, 
                                      double f, 
                                      double g, 
                                      double h, 
                                      double i, 
                                      double j, 
                                      double k, 
                                      double l, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_DoubleCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb);

    public double end_ping(Ice.AsyncResult __result);

    public Blob[] getVision();

    public Blob[] getVision(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getVision();

    public Ice.AsyncResult begin_getVision(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getVision(Ice.Callback __cb);

    public Ice.AsyncResult begin_getVision(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getVision(Callback_VisionInterface_getVision __cb);

    public Ice.AsyncResult begin_getVision(java.util.Map<String, String> __ctx, Callback_VisionInterface_getVision __cb);

    public Ice.AsyncResult begin_getVision(IceInternal.Functional_GenericCallback1<Blob[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getVision(IceInternal.Functional_GenericCallback1<Blob[]> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getVision(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<Blob[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getVision(java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<Blob[]> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Blob[] end_getVision(Ice.AsyncResult __result);
}
