// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `VisionModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VisionModule;

public final class VisionInterfaceHolder extends Ice.ObjectHolderBase<VisionInterface>
{
    public
    VisionInterfaceHolder()
    {
    }

    public
    VisionInterfaceHolder(VisionInterface value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof VisionInterface)
        {
            value = (VisionInterface)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _VisionInterfaceDisp.ice_staticId();
    }
}
